### ISSUE TITLE
Cached test items are being added when save has failed

### ISSUE THREAD

**Issue by stathismor** [yedpodtrzitko/pynamock#1]
I have a model that uses a custom attribute, which can raise an exception on `serialize`. This causes `save` to fail, but the invalid items can end up in `_test_items`. This can later cause `teardown` to fail, as `pynamodb` item's `delete` function still goes through `serialize` and fails. But the invalid items shouldn't be saved in the first place anyway. I've fixed it doing this:
```
        def save_override(self, *args, **kwargs):
            return_value = original_save(self, *args, **kwargs)

            if cls.class_data:
                cls._class_items.append(self)
            else:
                cls._test_items.append(self)

            return return_value
```

**Comment by yedpodtrzitko** [comment]
Hi,
thanks for the report. Could you please provide a traceback for such error? I don't use D/PynamoDB anymore, so I don't have the orchestration set up, but it sounds like a trivial fix. 

Thank you.

**Comment by stathismor** [comment]
I am not sure a detailed stacktrace would help here, as the error occurs on teardown, as an effect of the actual bug. Maybe I am wrong, but in my mind the bug is obvious, if you look at the current version of the code:
```
            if cls.class_data:
                cls._class_items.append(self)
            else:
                cls._test_items.append(self)

            return original_save(self, *args, **kwargs)
```
`_test_items` will be appended, if `original_save` raises an error. I assume you do not want that, because the items were never actually saved in the db, but the local `_test_items` will contain them. In my case the error happens on the `serialize` function of an attribute. And in the way `pynamodb` works, `serialize` will run on `item.delete`, so when the mixin code does it's teardown, and trying to delete all cached `_test_items`, it will eventually fail.

Here is what the console shows, although I said it might not help:
```
self = <test_profile.TestProfile object at 0x7ffa8c1e8ac8>

    def teardown(self):
        for item in self._test_items:
>           item.delete()

pynamock/mixins.py:82: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ve/lib/python3.6/site-packages/pynamodb/models.py:323: in delete
    args, kwargs = self._get_save_args(attributes=False, null_check=False)
ve/lib/python3.6/site-packages/pynamodb/models.py:1167: in _get_save_args
    serialized = self._serialize(null_check=null_check)
ve/lib/python3.6/site-packages/pynamodb/models.py:1323: in _serialize
    serialized = self._serialize_value(attr, value, null_check)
ve/lib/python3.6/site-packages/pynamodb/models.py:1351: in _serialize_value
    serialized = attr.serialize(value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <profile.attributes.LocationAttribute object at 0x7ffa8d129550>, value = 'TestLocation'

    def serialize(self, value):
        if value not in _LOCATIONS:
            raise LocationError(f'{value} is not a valid location.',
>                                  self.attr_name)
E           profile.attributes.LocationError: TestLocation is not a valid location.

profile/attributes.py:36: LocationError
```

**Comment by yedpodtrzitko** [comment]
Hi,
sorry for the delay. 

I pushed a (blind) fix, which should fix the problem. Let me know if that works. Thanks.


relevant commit: https://github.com/yedpodtrzitko/pynamock/commit/19bf863981fdd36f55399cb825c2dc9010711687

**Comment by stathismor** [comment]
Yes, that worked, thanks!
